# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/memoryAf/memoryAf.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memoryAf || ORIG_REF_NAME==memoryAf} -quiet] -quiet

# IP: bd/memoryAf/ip/memoryAf_axi_bram_ctrl_0_bram_0/memoryAf_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memoryAf_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==memoryAf_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/memoryAf/ip/memoryAf_blk_mem_gen_0_1/memoryAf_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memoryAf_blk_mem_gen_0_1 || ORIG_REF_NAME==memoryAf_blk_mem_gen_0_1} -quiet] -quiet

# Block Designs: bd/RegFile/RegFile.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFile || ORIG_REF_NAME==RegFile} -quiet] -quiet

# IP: bd/RegFile/ip/RegFile_blk_mem_gen_0_0/RegFile_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFile_blk_mem_gen_0_0 || ORIG_REF_NAME==RegFile_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/RegFile/ip/RegFile_blk_mem_gen_0_1/RegFile_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFile_blk_mem_gen_0_1 || ORIG_REF_NAME==RegFile_blk_mem_gen_0_1} -quiet] -quiet

# XDC: /home/afonso/Documents/VesPA-CPU_MEM_italian/VesPA-CPU_MEM_italian/VesPA Version 8bit ROM/aula.gen/sources_1/bd/memoryAf/memoryAf_ooc.xdc

# XDC: /home/afonso/Documents/VesPA-CPU_MEM_italian/VesPA-CPU_MEM_italian/VesPA Version 8bit ROM/aula.gen/sources_1/bd/RegFile/RegFile_ooc.xdc
